MONGODB:
  # Complete mongodb uri with authentication and arguments will be appended to uri as query parameters
  URI: "mongodb://192.168.1.104:27017"
  ARGUMENTS: ""
  DATABASE: "campaigns"
JWT:
  # In seconds, default 24 hours
  EXPIRY_TIME: 86400
  SECRET: "iLFwO0exwQTwJUBdgaGGRKt3T"
# In minutes, default to 3 minutes
IN_MEMORY_CACHE_EXPIRY: 3
# default, @options <<docker, childProcess>>
WORKER_TYPE: 'docker'
DOCKER:
  # default localhost, docker manager's url
  HOST: 127.0.0.1
  # default 2375
  PORT: 1234
  # default false, required for tls based authentication
  TLS_VERIFY: false
  CA: 'path/to/file/ca.pem'
  CERT: 'path/to/file/cert.pem'
  KEY: 'path/to/file/key.pem'
  # Volume point connected to master process
  ASSETS_HOST_PATH: /Users/parvez/Private/campaigns/backend/assets
  # Fetch worker logs and show it on master process
  FETCH_LOGS_FROM_WORKER: true
  # default '', network of docker container
  WORKER_NETWORK: my-network
  WORKER_IMAGE:

